// Code generated by goctl. DO NOT EDIT.
// Source: online.proto

package server

import (
	"context"

	"lightIM/rpc/online/internal/logic"
	"lightIM/rpc/online/internal/svc"
	"lightIM/rpc/online/types"
)

type OnlineServer struct {
	svcCtx *svc.ServiceContext
	types.UnimplementedOnlineServer
}

func NewOnlineServer(svcCtx *svc.ServiceContext) *OnlineServer {
	return &OnlineServer{
		svcCtx: svcCtx,
	}
}

func (s *OnlineServer) UserOnline(ctx context.Context, in *types.UserOfflineReq) (*types.UserOfflineResp, error) {
	l := logic.NewUserOnlineLogic(ctx, s.svcCtx)
	return l.UserOnline(in)
}

func (s *OnlineServer) UserOffline(ctx context.Context, in *types.UserOfflineReq) (*types.UserOfflineResp, error) {
	l := logic.NewUserOfflineLogic(ctx, s.svcCtx)
	return l.UserOffline(in)
}

func (s *OnlineServer) GetRoute(ctx context.Context, in *types.RouteReq) (*types.RouteResp, error) {
	l := logic.NewGetRouteLogic(ctx, s.svcCtx)
	return l.GetRoute(in)
}
