// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"lightIM/rpc/user/internal/logic"
	"lightIM/rpc/user/internal/svc"
	"lightIM/rpc/user/types"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	types.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) SignIn(ctx context.Context, in *types.SignInReq) (*types.SignInResp, error) {
	l := logic.NewSignInLogic(ctx, s.svcCtx)
	return l.SignIn(in)
}

func (s *UserServer) SignUp(ctx context.Context, in *types.SignUpReq) (*types.SignUpResp, error) {
	l := logic.NewSignUpLogic(ctx, s.svcCtx)
	return l.SignUp(in)
}
