// Code generated by goctl. DO NOT EDIT.
package types

type AddFriendReq struct {
	From int64 `json:"from"`
	To   int64 `json:"to"`
}

type AddFriendResp struct {
	Base
}

type Base struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type DelFriendReq struct {
	From int64 `json:"from"`
	To   int64 `json:"to"`
}

type DelFriendResp struct {
	Base
}

type FriendListReq struct {
	From int64 `json:"from"`
}

type FriendListResp struct {
	Base
	Friends []UserInfo `json:"friends"`
}

type SignInReq struct {
	Tel string `json:"tel"`
	Pwd string `json:"pwd"`
}

type SignInResp struct {
	Base
	Token string `json:"token"`
}

type SignUpReq struct {
	Tel      string `json:"tel"`
	NickName string `json:"nickName"`
	Pwd      string `json:"pwd"`
	Code     string `json:"code"`
}

type SignUpResp struct {
	Base
}

type UserInfo struct {
	Uid      int64  `json:"uid"`
	Tel      string `json:"tel"`
	NickName string `json:"nick_name"`
}

type VerifyCodeReq struct {
	Tel string `json:"tel"`
}

type VerifyCodeResp struct {
	Base
}
