// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "lightIM/api/internal/handler/login"
	relationship "lightIM/api/internal/handler/relationship"
	"lightIM/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 登录
				Method:  http.MethodPost,
				Path:    "/signin",
				Handler: login.SignInHandler(serverCtx),
			},
			{
				// 账号注册
				Method:  http.MethodPost,
				Path:    "/signup",
				Handler: login.SignUpHandler(serverCtx),
			},
			{
				// 请求验证码
				Method:  http.MethodPost,
				Path:    "/verifycode",
				Handler: login.VerifyCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/login"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 好友请求
				Method:  http.MethodPost,
				Path:    "/friend/add",
				Handler: relationship.AddFriendHandler(serverCtx),
			},
			{
				// 删除好友
				Method:  http.MethodPost,
				Path:    "/friend/del",
				Handler: relationship.DelFriendHandler(serverCtx),
			},
			{
				// 请求好友列表
				Method:  http.MethodGet,
				Path:    "/friend/list",
				Handler: relationship.GetFriendListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/relationship"),
	)
}
