// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "lightIM/api/internal/handler/login"
	"lightIM/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 登录
				Method:  http.MethodPost,
				Path:    "/signin",
				Handler: login.SignInHandler(serverCtx),
			},
			{
				// 账号注册
				Method:  http.MethodPost,
				Path:    "/signup",
				Handler: login.SignUpHandler(serverCtx),
			},
			{
				// 请求验证码
				Method:  http.MethodPost,
				Path:    "/verifycode",
				Handler: login.VerifyCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/login"),
	)
}
