// Code generated by goctl. DO NOT EDIT.
package history

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/monc"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

var prefixHistoryCacheKey = "cache:history:"

type historyModel interface {
	Insert(ctx context.Context, data *History) error
	FindOne(ctx context.Context, id string) (*History, error)
	Update(ctx context.Context, data *History) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
}

type defaultHistoryModel struct {
	conn *monc.Model
}

func newDefaultHistoryModel(conn *monc.Model) *defaultHistoryModel {
	return &defaultHistoryModel{conn: conn}
}

func (m *defaultHistoryModel) Insert(ctx context.Context, data *History) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	key := prefixHistoryCacheKey + data.ID.Hex()
	_, err := m.conn.InsertOne(ctx, key, data)
	return err
}

func (m *defaultHistoryModel) FindOne(ctx context.Context, id string) (*History, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data History
	key := prefixHistoryCacheKey + id
	err = m.conn.FindOne(ctx, key, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHistoryModel) Update(ctx context.Context, data *History) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()
	key := prefixHistoryCacheKey + data.ID.Hex()
	res, err := m.conn.UpdateOne(ctx, key, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultHistoryModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}
	key := prefixHistoryCacheKey + id
	res, err := m.conn.DeleteOne(ctx, key, bson.M{"_id": oid})
	return res, err
}
